version: '3'
services: 
    app:
        image: app
        build: .
        container_name: 'api'
        ports: 
            - "8000:8000"
        volumes: 
            - ./:/core
        networks: 
            - local


networks: 
    local: