version: '3'
services: 
    wishlist:
        build: .
        container_name: "api"
        ports: 
            - "8000:8000"
        volumes: 
            - ./:/app
        networks: 
            - local


networks: 
    local: